name: CI

on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.10', '3.12', '3.13', '3.14']
        rf-version: ['7.3.2']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "robotframework==${{ matrix.rf-version }}" -r requirements.txt
    - name: Sanity
      run: |
        python -c "import robot; print(robot.__version__)"
        python -c "import flask, tornado; print(flask.__version__)"
    - name: Unit tests
      run: |
        python -m rfhub --version
